### ISSUE TITLE
Interesting project

### ISSUE THREAD

**Issue by rockstardev** [davidtimovski/sapphire-notes#6]
I'm kinda curious why develop another notes app when there are so many out there already.

Pozdrav bratu Makedoncu ;)

**Comment by rockstardev** [comment]
Aha: https://www.davidtimovski.com/blog/13/personal-assistant

Link in blog post to My Project's doesn't work though, url changed from https://www.davidtimovski.com/MyProjects to https://www.davidtimovski.com/my-projects

**Comment by davidtimovski** [comment]
Good question.

I had been following a lot of online discussion on cross-platform desktop development in threads about Electron apps. Basically, many people hate Electron apps for being slow and memory hungry, and are first in line to suggest alternatives that are not really alternatives.

You can do cross-platform GUI development for desktop in many technologies but they all have pros and cons. Electron apps are slow and memory hungry but produce beautiful interfaces and are fairly easy to develop - which is why they're so popular right now. C++/Qt apps are very fast but often ugly looking. It is possible but much more difficult/expensive to produce a UI with C++ that would compete with the one of Electron apps.

WPF and UWP are great technologies but Windows only. Microsoft's new MAUI platform is too young and also won't provide official support for Linux. Xamarin is a fairly hated technology (at least according to Stack Overflow's yearly surveys) so that one's out. And there's a whole plethora of obscure .NET options like Avalonia, Uno Platform, and Qt.NET. I just went on board with the one I liked most.

So to answer your question, I did it to see what's possible with cross-platform GUI desktop technologies. Because if I only read internet forums I might be convinced of a lot of things are simply not true. People will say all kinds of crazy stuff (like C++/Qt is a direct alternative for Electron) just to win an internet battle.

Sapphire Notes is an exercise in: the only way to know is to try.

**Comment by davidtimovski** [comment]
Stay tuned for my upcoming v0.3.0 themes update where Sapphire Notes will look.. a little less ugly.

**Comment by rockstardev** [comment]
Got it - self-improvement is a demanding road ;)

I'm looking forward to v0.3.0 and will follow your work.
